Integrate php sdk
mobbexco/wp-travel pull request #2
Opened 2023-04-14 16:56 UTC by mobbexLuis

2023-04-14 16:57 UTC, mobbexLuis commented
LGTM

2023-05-05 14:01 UTC, jlmobbex requested changes

2023-05-05 14:01 UTC, jlmobbex commented on wp-travel-mobbex.php
> +// Include necesary classes from Sdk
Estas clases ya se requieren mediante el autoload

2023-05-05 14:01 UTC, jlmobbex commented on wp-travel-mobbex.php
> +        'wp_travel' . WP_TRAVEL_VERSION,
No hace falta concatenar la versión al primer param (sólo refiere al nombre de la plataforma)

2023-05-05 14:01 UTC, jlmobbex commented on wp-travel-mobbex.php
> +        str_replace('www.', '', parse_url(home_url(), PHP_URL_HOST)),
No hace falta realizar el parseo y remplazo debido a que de eso se encarga el sdk. Podés simplemente pasar el valor de `home_url()`

2023-05-05 14:01 UTC, jlmobbex commented on wp-travel-mobbex.php
> +            'sdk'       => class_exists('\Composer\InstalledVersions') ? \Composer\InstalledVersions::getVersion('mobbexco/php-plugins-sdk') : '',
A esto hay que añadirle un chequeo de si está instalado el paquete (ver https://github.com/mobbexco/prestashop/pull/146#discussion_r1177134925)

2023-05-05 14:01 UTC, jlmobbex commented on includes/helper/class-booking-helper.php
> +namespace Mobbex\WPT\Helper;
En este archivo faltó actualizar el namespace del checkout (se está usando `\Mobbex\Checkout` y el que está en el sdk es `\Mobbex\Modules\Checkout`). Revisar si no cambiaron los params que recibe también

2023-05-05 14:01 UTC, jlmobbex commented on includes/helper/class-booking-helper.php
> +namespace Mobbex\WPT\Helper;
Una cosa más, en la clase checkout del sdk se usa un array `addresses` para todas las direcciones y acá se está mandando todo junto en el customer, que es la forma antigua en la que se mandaba. Hay que actualizar esto

2023-05-05 19:10 UTC, jlmobbex requested changes

2023-05-05 19:10 UTC, jlmobbex commented on includes/helper/class-booking-helper.php
>              'address'        => trim(preg_replace('/[0-9]/', '', (string) $traveller['address'])),
Estas keys también se actualizaron en el array de addresses. Fijate como está documentada cada posición en el el construct del checkout

2023-05-05 22:49 UTC, jlmobbex commented on includes/helper/class-booking-helper.php
>              'address'        => trim(preg_replace('/[0-9]/', '', (string) $traveller['address'])),
Un comentario más. Al cargar el autoload en el archivo principal agregale la constante `__DIR__` justo antes de la dirección, esto para que la ruta sea absoluta en vez de relativa (esto causa errores en algunas instalaciones). Podés basarte en master de woocommerce.

2023-06-28 14:17 UTC, jlmobbex requested changes

2023-06-28 14:17 UTC, jlmobbex commented on includes/helper/class-booking-helper.php
> +            'type'          => 'Billing',
Por las dudas de que el servicio haga un chequeo estricto del string, creo que sería mejor poner `billing` en minúsculas

2023-06-28 14:17 UTC, jlmobbex commented on includes/helper/class-booking-helper.php
> +            'street'        => trim(preg_replace('/[0-9]/', '', (string) $traveller['address'])),
Esta query de regex remplazaría todos los números, y en ciudades costeras se complica porque las calles tienen números en el nombre (ej. Avenida 3). Por esta razón en el resto de plataformas usamos una query que sólo separa los últimos dígitos que estén juntos: https://github.com/mobbexco/woocommerce/blob/01e2ad553c3d5de9dce4409c12438f602c1a3547/Model/Checkout.php#L134

2023-06-29 13:03 UTC, jlmobbex approved these changes

2023-06-29 13:06 UTC, merged