add new method to check if debug mode is on
mobbexco/wp-travel pull request #3
Opened 2023-04-14 17:06 UTC by mobbexLuis

2023-04-14 17:07 UTC, mobbexLuis commented
LGTM

2023-07-06 15:02 UTC, jlmobbex requested changes

2023-07-06 15:02 UTC, jlmobbex commented on includes/helper/class-booking-helper.php
> +use Mobbex\Platform;
Esta línea sólo es necesaria cuando se quiere evitar el namespace completo de la clase. Ejemplo `$platform = new Platform();`, pero lo más recomendable es utilizar namespaces completos así que no es necesario declarar el uso

2023-07-06 15:02 UTC, jlmobbex commented on includes/helper/class-booking-helper.php
> +    public function get_endpoint_url($query, $rest)
Habría que documentar los params y tipo de retorno. Por otro lado, el param `$rest` podría renombrarse a `endpoint`, así queda más claro que hay que pasar. Mismo caso con query, que además podría ser opcional y ser el segundo param en lugar del primero (dado que el nombre del método pone el foco en el endpoint, a diferencia de la de wordpress `add_query_arg` que se usaba antes).

2023-07-06 15:02 UTC, jlmobbex commented on includes/helper/class-booking-helper.php
>              add_query_arg(compact('booking_id', 'token', 'nonce'), get_rest_url(null, 'wpt/mobbex/payment/callback')),
Se podría usar el método de `get_endpoint_url` acá también, así queda más homogéneo y si tenemos que meter después un cambio lo metemos una sóla vez.

2023-07-13 16:33 UTC, jlmobbex approved these changes
Una belleza!

2023-07-13 16:34 UTC, merged